webtalk_init -webtalk_dir C:/Users/zhangyu/Desktop/Research18/ip_repo/Conways_zedboard/Conways_zedboard.sim/sim_1/behav/xsim.dir/Top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul 17 09:46:32 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1577090" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f99fb0b755d45e5b9e31d9eba377f570" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1c7868b8766342b8abedc3c1ab7b430c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "9" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "2286 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "706 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "28822" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "22843" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "1032" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "9.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "261928_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3190607921 -regid "" -xml C:/Users/zhangyu/Desktop/Research18/ip_repo/Conways_zedboard/Conways_zedboard.sim/sim_1/behav/xsim.dir/Top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/zhangyu/Desktop/Research18/ip_repo/Conways_zedboard/Conways_zedboard.sim/sim_1/behav/xsim.dir/Top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/zhangyu/Desktop/Research18/ip_repo/Conways_zedboard/Conways_zedboard.sim/sim_1/behav/xsim.dir/Top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
